# Generated by Django 6.0.4 on 2026-05-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('remoteok', 'RemoteOK'), ('wellfound', 'Wellfound'), ('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('manual', 'Manually Added')], default='manual', max_length=20)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('description', models.TextField(blank=True)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags/Skills associated with the job')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['source'], name='jobs_job_source_e2155e_idx'), models.Index(fields=['is_active'], name='jobs_job_is_acti_b6ae73_idx')],
            },
        ),
    ]
