# Generated by Django 6.0.4 on 2026-05-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='[YOUR_NAME]', max_length=100)),
                ('role', models.CharField(default='[YOUR_ROLE]', max_length=100)),
                ('tagline', models.TextField(default='[YOUR_TAGLINE]')),
                ('bio', models.TextField(default='[YOUR_BIO]')),
                ('experience_summary', models.CharField(default='[YOUR_EXPERIENCE]', max_length=100)),
                ('location', models.CharField(default='[YOUR_LOCATION]', max_length=100)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
            options={
                'verbose_name_plural': 'About Info',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('start_date', models.CharField(help_text='e.g. Jan 2020', max_length=50)),
                ('end_date', models.CharField(help_text='e.g. Dec 2022 or Present', max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Experience',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('tech_stack', models.CharField(help_text='Comma separated skills', max_length=200)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('live_demo_url', models.URLField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome or DevIcon class', max_length=50)),
                ('proficiency', models.IntegerField(default=80, help_text='Percentage 0-100')),
                ('category', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Tools', 'Tools')], default='Frontend', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text='FontAwesome class e.g. fab fa-github', max_length=50)),
            ],
        ),
    ]
